version: '3'
services:
  app:
    build:
      context: ./app
    command: python manage.py runserver 0.0.0.0:80000
    ports:
      - 80:80
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres