version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: app
      POSTGRES_DB: hydrazine

  app:
    build:
      context: ./app
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - db

